config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  root "home#index"
  get "/patients", to: "patients#index"
  get "/patients/visits", to: "patients#visits"
  get "/visits", to: "visits#index"

  resources :visits, only: [:new, :create, :edit, :update, :destroy] do
    collection do
      get 'available_times'
    end
  end
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
  attr_accessor :visit_date, :visit_time

  # simple validation
  validates :patient_id, presence: true
  validates :patient_id, numericality: { only_integer: true }
  validate :check_patient_exists

  validates :doctor_id, presence: true
  validates :doctor_id, numericality: { only_integer: true }
  validate :check_doctor_exists

  validates :visit_date, presence: true
  validate :check_visit_date
  validates :visit_time, presence: true
  validate :check_visit_time

  validates :visit_price, presence: true
  validate :check_visit_price

  # db validations
  validate :check_unique_visit_datetime_for_doctor

  # other
  before_validation :combine_date_and_time

  private

  def check_patient_exists
    if patient_id.present? && !Patient.exists?(patient_id)
      errors.add(:patient_id, "nie istnieje") unless errors[:patient_id].include?("nie istnieje")
    end
  end

  def check_doctor_exists
    if doctor_id.present? && !Doctor.exists?(doctor_id)
      errors.add(:doctor_id, "nie istnieje") unless errors[:doctor_id].include?("nie istnieje")
    end
  end

  def check_visit_date
    return if visit_date.blank? || visit_date.nil?
    visit_date_obj = visit_date.is_a?(String) ? Date.parse(visit_date) : visit_date

    if !(1..5).include?(visit_date_obj.wday)
      errors.add(:visit_date, "musi przypadać na dzień od poniedziałku do piątku")
    elsif visit_date_obj.present? && visit_date_obj < Date.current
      errors.add(:visit_date, 'nie może być z przeszłości')
    end
  end

  def check_visit_time
    return if visit_time.blank?
    visit_time_obj = visit_time.is_a?(String) ? Time.parse(visit_time) : visit_time

    unless (8..16).cover?(visit_time_obj.hour) && (visit_time_obj.min % 20).zero?
      errors.add(:visit_time, "musi być w zakresie od 8:00 do 16:00 i być wielokrotnością 20 minut")
    end
  rescue ArgumentError
    errors.add(:visit_time, "nieprawidłowy format czasu")
  end

  def check_visit_price
    return if visit_price.blank?

    unless visit_price.to_f >= 0
      errors.add(:visit_price, "musi być większa lub równa 0")
    end
  end

  # db validations
  def check_unique_visit_datetime_for_doctor
    return if visit_datetime.blank? || doctor_id.blank?

    existing_visits = Visit.where(visit_datetime: visit_datetime, doctor_id: doctor_id)
    existing_visits = existing_visits.where.not(id: self.id) if self.persisted?  # Ignore actual visit when editing

    if existing_visits.exists?
      errors.add(:visit_time, "jest zajęty dla danego lekarza")
    end
  end

  # other
  def combine_date_and_time
    return if visit_date.blank? || visit_time.blank?

    self.visit_datetime = DateTime.parse("#{visit_date} #{visit_time}")
  rescue ArgumentError
    errors.add(:visit_datetime, "nieprawidłowy format daty i czasu")
  end

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  def index
    # Patients
    @visits = Visit.includes(:doctor, :patient).all
    items = 10

    @pagy, @visits = pagy(@visits, items: items)
  end

  def new
    @visit = Visit.new(patient_id: params["patient_id"])
    @patient_name = '#' + @visit.patient_id.to_s + ' ' + Patient.find_by(id: @visit.patient_id)&.name + ' ' + Patient.find_by(id: @visit.patient_id)&.surname
    @doctors = Doctor.all
  end

  def create
    @visit = Visit.new(visit_params)
    @patient_name = '#' + @visit.patient_id.to_s + ' ' + Patient.find_by(id: @visit.patient_id)&.name + ' ' + Patient.find_by(id: @visit.patient_id)&.surname
    @doctors = Doctor.all

    if @visit.save
      render :new_completed
    else
      render :new
    end
  end

  def edit
    @visit = Visit.find(params[:id])
    @visit.visit_date = @visit.visit_datetime.strftime('%Y-%m-%d')
    @visit.visit_time = @visit.visit_datetime.strftime('%H:%M')

    @patient_name = '#' + @visit.patient_id.to_s + ' ' + Patient.find_by(id: @visit.patient_id)&.name + ' ' + Patient.find_by(id: @visit.patient_id)&.surname
    @doctors = Doctor.all

    @visit_date = @visit.visit_datetime.strftime('%Y-%m-%d')
    @visit_time = @visit.visit_datetime.strftime('%H:%M')
  end

  def update
    @visit = Visit.find(params[:id])
    @patient_name = '#' + @visit.patient_id.to_s + ' ' + Patient.find_by(id: @visit.patient_id)&.name + ' ' + Patient.find_by(id: @visit.patient_id)&.surname
    @doctors = Doctor.all  # Dostarcz listę lekarzy

    if @visit.update(visit_params)
      render :edit_completed
    else
      render :edit
    end
  end

  def destroy
    @destroy_success = true

    begin
      @visit = Visit.find(params[:id])
      @destroy_success = @visit.destroy
    rescue ActiveRecord::RecordNotFound
      @destroy_success = false
    end

    render :destroy
  end

  def available_times
    date = params[:date]
    doctor_id = params[:doctor_id]
    ignore_visit_id = params[:ignore_visit_id]

    # Check: Monday to Friday
    selected_date = Date.parse(date)
    unless (1..5).include?(selected_date.wday)
      render json: { error: 'Wybrana data nie jest dostępna' }, status: :unprocessable_entity
      return
    end

    # Check: Doctor is exists
    doctor = Doctor.find_by(id: doctor_id)
    unless doctor
      render json: { error: 'Lekarz nie istnieje' }, status: :unprocessable_entity
      return
    end

    # Get: Times
    existing_visits = Visit.where('doctor_id = ? AND visit_datetime >= ? AND visit_datetime <= ?', doctor_id, selected_date.beginning_of_day, selected_date.end_of_day)
    existing_visits = existing_visits.pluck(:visit_datetime).map { |v| v.strftime('%H:%M') }

    # Ignore specific visit
    if ignore_visit_id.present?
      ignore_visit = Visit.find_by(id: ignore_visit_id)

      if ignore_visit && ignore_visit.doctor_id.to_i == doctor_id.to_i && ignore_visit.visit_datetime.to_date == selected_date
        existing_visits -= [ignore_visit.visit_datetime.strftime('%H:%M')]
      end
    end

    all_times = ("8".."16").flat_map do |h|
      ("00".."40").step(20).flat_map do |m|
        next if h == "16" && (m == "20" || m == "40")

        h_with_zero = h.length == 1 ? "0#{h}" : h
        "#{h_with_zero}:#{m}"
      end
    end.compact

    available_times = all_times - existing_visits

    render json: { available_times: available_times }
  end


  private

  def visit_params
    params.require(:visit).permit(:patient_id, :doctor_id, :visit_price, :visit_date, :visit_time)
  end
end

app/views/visits/destroy.html.erb
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1 class="m-0">Usuwanie wizyty</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/visits/">Wizyty</a></li>
            <li class="breadcrumb-item active">Usuwanie wizyty</li>
        </ol>
        </div><!-- /.col -->
    </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
    <!-- Main row -->
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Wizyta > Usuwanie wizyty</h3>
                </div>
                <div class="card-body">
                    <% if @destroy_success %>
                    <span class="text text-success h4">Wizyta została usunięta pomyślnie.</span>
                    <% else %>
                    <span class="text text-danger h4">Wystąpił problem podczas usuwania wizyty.</span>
                    <% end %>
                </div>
                <div class="card-footer">
                    <a href="/visits/" class="btn btn-secondary">Lista wizyt</a>
                    <a href="/" class="btn btn-secondary ml-2">Home</a>
                </div>
            </div>
        </div>
    </div>
    <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->

app/views/visits/edit.html.erb
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Edytacja wizyty</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    <li class="breadcrumb-item"><a href="/visits/">Wizyty</a></li>
                    <li class="breadcrumb-item active">Edytuj</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section id="visits_new" class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Formularz edytowania wizyty: #<%= params[:id] %></h3>
                    </div>
                    <%= form_for @visit do |f| %>
                    <%= f.hidden_field :patient_id %>
                    <inpu name="visit_time" type="hidden" value="<%= @visit["visit_time"] %>">
                    <div class="card-body">
                        <div class="row">
                            <div class="form-group col-6 <%= 'has-error' if @visit.errors.include?(:patient_id) %>">
                                <%= f.label 'Pacjent' %>
                                <input type="text" class="form-control<%= @visit.errors.include?(:patient_id) ? ' is-invalid' : '' %>" value="<%=@patient_name%>" disabled>
                                <% if @visit.errors.include?(:patient_id) %>
                                <span class="error invalid-feedback" style="display: block"><%= @visit.errors.full_messages_for(:patient_id)[0] %></span>
                                <% end %>
                            </div>
                            <div class="form-group col-6 <%= 'has-error' if @visit.errors.include?(:doctor_id) %>">
                                <%= f.label 'Doktor' %>
                                <%= f.select :doctor_id, options_for_select(@doctors.map { |c| [(c.name + ' ' + c.surname), c.id] }, @visit.doctor_id), { include_blank: '' }, class: "form-control #{'is-invalid' if @visit.errors.include?(:doctor_id)}" %>
                                <% if @visit.errors.include?(:doctor_id) %>
                                <span class="error invalid-feedback" style="display: block"><%= @visit.errors.full_messages_for(:doctor_id)[0] %></span>
                                <% end %>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-6 <%= 'has-error' if @visit.errors.include?(:visit_date) %>">
                                <%= f.label 'Data wizyty' %>
                                <%= f.text_field :visit_date, class: "form-control #{'is-invalid' if @visit.errors.include?(:visit_date)}", placeholder: 'yyyy-mm-dd', autocomplete: 'off' %>
                                <% if @visit.errors.include?(:visit_date) %>
                                    <span class="error invalid-feedback" style="display: block"><%= @visit.errors.full_messages_for(:visit_date)[0] %></span>
                                <% end %>
                            </div>

                            <div class="form-group col-6 <%= 'has-error' if @visit.errors.include?(:visit_time) %>">
                                <%= f.label 'Godzina wizyty' %>
                                <%= f.select :visit_time, options_for_select([f.object.visit_time], selected: f.object.visit_time), { include_blank: 'Wybierz godzinę' }, class: "form-control #{'is-invalid' if @visit.errors.include?(:visit_time)}" %>
                                <% if @visit.errors.include?(:visit_time) %>
                                    <span class="error invalid-feedback" style="display: block"><%= @visit.errors.full_messages_for(:visit_time)[0] %></span>
                                <% end %>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-6 <%= 'has-error' if @visit.errors.include?(:visit_price) %>">
                                <%= f.label 'Cena wizyty' %>
                                <%= f.text_field :visit_price, class: "form-control #{'is-invalid' if @visit.errors.include?(:visit_price)}", placeholder: 'Cena wizyty', autocomplete: 'off' %>
                                <% if @visit.errors.include?(:visit_price) %>
                                <span class="error invalid-feedback" style="display: block"><%= @visit.errors.full_messages_for(:visit_price)[0] %></span>
                                <% end %>
                            </div>
                            <div class="form-group col-6">
                                <%= f.label 'Waluta' %>
                                <input type="text" class="form-control" value="PLN" disabled>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <%= f.submit 'Zarejestruj wizyte', class: 'btn btn-primary' %>
                    </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    document.ignore_visit_id = <%= params[:id] %>;
</script>

app/views/visits/edit_completed.html.erb
<div class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1 class="m-0">Edytacja wizyty</h1>
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/visits/">Wizyty</a></li>
            <li class="breadcrumb-item active">Edytuj</li>
        </ol>
        </div>
    </div>
    </div>
</div>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Wizyta > Edytowanie wizyty zakończone</h3>
                    </div>
                    <div class="card-body">
                        <% if @visit.persisted? %>
                        <span class="text text-success h4">Wizyta została zmieniona pomyślnie.</span>
                        <% else %>
                        <span class="text text-danger h4">Nie udało się edytować wizyty.</span>
                        <% end %>
                    </div>
                    <div class="card-footer">
                        <a href="/visits/" class="btn btn-secondary">Lista wizyt</a>
                        <a href="/" class="btn btn-secondary ml-2">Home</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/visits/index.html.erb
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1 class="m-0">Wizyty</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Wizyty</li>
        </ol>
        </div><!-- /.col -->
    </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
    <!-- Main row -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Lista wizyt</h3>
                    </div>
                    <% if @visits.length > 0 %>
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover text-nowrap">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Pacjent</th>
                                    <th>Lekarz</th>
                                    <th>Data</th>
                                    <th>Czas</th>
                                    <th>Cena</th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @visits.each do |visit| %>
                                <tr data-widget="expandable-table" aria-expanded="false">
                                    <td><%= visit.id %></td>
                                    <td><%= visit.patient.name + ' ' + visit.patient.surname %></td>
                                    <td><%= visit.doctor.name + ' ' + visit.doctor.surname %></td>
                                    <td><%= visit.visit_datetime.strftime('%Y-%m-%d') %></td>
                                    <td><%= visit.visit_datetime.strftime('%H:%M') %></td>
                                    <td><%= visit.visit_price.to_s + ' ' + visit.visit_currency.to_s %></td>
                                </tr>
                                <tr class="expandable-body">
                                    <td colspan="6">
                                        <div class="d-flex align-items-center justify-content-center">
                                            <%= link_to "Edytuj wizyte", edit_visit_path(visit), class: "btn btn-block btn-warning mt-0 ml-2" %>
                                            <%= link_to "Usuń wizyte", visit, method: :delete, data: { confirm: "Czy jesteś pewien że chcesz usunąc wizyte?" }, class: "btn btn-block btn-danger mt-0 ml-2" %>
                                        </div>
                                    </td>
                                </tr>
                                <% end %>
                            </tbody>
                        </table>
                        <div class="mt-3 d-flex align-items-center justify-content-center">
                            <%== pagy_bootstrap_nav(@pagy, prev: 'Wcześniej', next: 'Dalej') %>
                        </div>
                    </div>
                    <% else %>
                    <div class="card-body text-center">
                        <span class="text text-danger h4">Aktualnie nie ma żadnej wizyty.</span>
                    </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/visits/new.html.erb
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1 class="m-0">Rejestracja nowej wizyty</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/visits/">Wizyty</a></li>
            <li class="breadcrumb-item active">Nowa</li>
        </ol>
        </div><!-- /.col -->
    </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section id="visits_new" class="content">
    <div class="container-fluid">
    <!-- Main row -->
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Formularz nowej wizyty</h3>
                </div>
                <%= form_for @visit do |f| %>
                <%= f.hidden_field :patient_id %>
                <inpu name="visit_time" type="hidden" value="<%= @visit["visit_time"] %>">
                <div class="card-body">
                    <div class="row">
                        <div class="form-group col-6 <%= 'has-error' if @visit.errors.include?(:patient_id) %>">
                            <%= f.label 'Pacjent' %>
                            <input type="text" class="form-control<%= @visit.errors.include?(:patient_id) ? ' is-invalid' : '' %>" value="<%=@patient_name%>" disabled>
                            <% if @visit.errors.include?(:patient_id) %>
                            <span class="error invalid-feedback" style="display: block"><%= @visit.errors.full_messages_for(:patient_id)[0] %></span>
                            <% end %>
                        </div>
                        <div class="form-group col-6 <%= 'has-error' if @visit.errors.include?(:doctor_id) %>">
                            <%= f.label 'Doktor' %>
                            <%= f.select :doctor_id, options_for_select(@doctors.map { |c| [(c.name + ' ' + c.surname), c.id] }, @visit.doctor_id), { include_blank: '' }, class: "form-control #{'is-invalid' if @visit.errors.include?(:doctor_id)}" %>
                            <% if @visit.errors.include?(:doctor_id) %>
                            <span class="error invalid-feedback" style="display: block"><%= @visit.errors.full_messages_for(:doctor_id)[0] %></span>
                            <% end %>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-6 <%= 'has-error' if @visit.errors.include?(:visit_date) %>">
                            <%= f.label 'Data wizyty' %>
                            <%= f.text_field :visit_date, class: "form-control #{'is-invalid' if @visit.errors.include?(:visit_date)}", placeholder: 'yyyy-mm-dd', autocomplete: 'off' %>
                            <% if @visit.errors.include?(:visit_date) %>
                                <span class="error invalid-feedback" style="display: block"><%= @visit.errors.full_messages_for(:visit_date)[0] %></span>
                            <% end %>
                        </div>

                        <div class="form-group col-6 <%= 'has-error' if @visit.errors.include?(:visit_time) %>">
                            <%= f.label 'Godzina wizyty' %>
                            <%= f.select :visit_time, options_for_select([f.object.visit_time], selected: f.object.visit_time), { include_blank: 'Wybierz godzinę' }, class: "form-control #{'is-invalid' if @visit.errors.include?(:visit_time)}" %>
                            <% if @visit.errors.include?(:visit_time) %>
                                <span class="error invalid-feedback" style="display: block"><%= @visit.errors.full_messages_for(:visit_time)[0] %></span>
                            <% end %>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-6 <%= 'has-error' if @visit.errors.include?(:visit_price) %>">
                            <%= f.label 'Cena wizyty' %>
                            <%= f.text_field :visit_price, class: "form-control #{'is-invalid' if @visit.errors.include?(:visit_price)}", placeholder: 'Cena wizyty', autocomplete: 'off' %>
                            <% if @visit.errors.include?(:visit_price) %>
                            <span class="error invalid-feedback" style="display: block"><%= @visit.errors.full_messages_for(:visit_price)[0] %></span>
                            <% end %>
                        </div>
                        <div class="form-group col-6">
                            <%= f.label 'Waluta' %>
                            <input type="text" class="form-control" value="PLN" disabled>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <%= f.submit 'Zarejestruj wizyte', class: 'btn btn-primary' %>
                </div>
                <% end %>
            </div>
        </div>
    </div>
    <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->

app/views/visits/new_completed.html.erb
<div class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1 class="m-0">Rejestracja nowej wizyty</h1>
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/visits/">Wizyty</a></li>
            <li class="breadcrumb-item active">Nowa</li>
        </ol>
        </div>
    </div>
    </div>
</div>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Wizyta > Rejestracja zakończona</h3>
                    </div>
                    <div class="card-body">
                        <% if @visit.persisted? %>
                        <span class="text text-success h4">Wizyta została zarejestrowana pomyślnie.</span>
                        <% else %>
                        <span class="text text-danger h4">Wystąpił problem podczas rejestrowania wizyty.</span>
                        <% end %>
                    </div>
                    <div class="card-footer">
                        <a href="/visits/" class="btn btn-secondary">Lista wizyt</a>
                        <a href="/" class="btn btn-secondary ml-2">Home</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>